name: music_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.12
  http: ^1.2.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/music/
    - assets/lyrics/